### ISSUE TITLE
console.log what is fisk?

### ISSUE THREAD

**Issue by srini-venigalla** [mariusbrataas/flowpoints.js#12]
Can someone explain what is fisk in console.log? When I click on a Flowpoint I am seeing fisk data in console.log..

**Comment by mariusbrataas** [comment]
Haha :D That's norwegian for "fish". I tend to use that as placeholder text for console.log while debugging. Fixed in [80f2199](https://github.com/mariusbrataas/flowpoints.js/commit/80f2199a05fcea352046afe8f19c5cac60cca2c1)
