### ISSUE TITLE
onLineClick function not firing for connected Flowpoints.

### ISSUE THREAD

**Issue by lisenkaci** [mariusbrataas/flowpoints.js#7]
Hello, I am having some issues. The onLineClick function is not firing at all when I click a line connection. The onClick works on the Flowspace and it does not fire when you click a line, but onLineClick does not fire. I am using React.  Any help would be appreciated it, Thank you.

**Comment by mariusbrataas** [comment]
Fixing this in upcoming update. Closing this issue for now
